language: ruby
before_install: gem install bundler && bundler -v
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
addons:
  code_climate:
    repo_token: a3efbc440cb5027fc10a3cfa845aab934cf8c48c27fa0b2ff34855933245aca1
